# Generated by Django 5.1.4 on 2025-01-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_profileimage_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profileimage",
            name="size",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
