# Generated by Django 5.1.4 on 2025-01-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_profileimage_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gender",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="country",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="firstname",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="lastname",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="state",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="profileimage",
            name="alt",
            field=models.CharField(default="Profile image", max_length=255),
        ),
        migrations.AlterField(
            model_name="profileimage",
            name="format",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="profileimage",
            name="mode",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="user", name="password", field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
