# Generated by Django 5.1.4 on 2025-01-27 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_gender_name_alter_profile_bio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="profileimage",
            name="format",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="profileimage",
            name="height",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="profileimage",
            name="mode",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="profileimage", name="size", field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="profileimage",
            name="width",
            field=models.IntegerField(null=True),
        ),
    ]
