# Generated by Django 5.1.4 on 2025-01-27 19:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="articles/article-images")),
                ("alt", models.CharField(max_length=255)),
                ("format", models.CharField(blank=True, max_length=255, null=True)),
                ("mode", models.CharField(blank=True, max_length=255, null=True)),
                ("size", models.FloatField(blank=True, null=True)),
                ("width", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Article Image",
                "verbose_name_plural": "Article Images",
            },
        ),
        migrations.AlterField(
            model_name="article",
            name="content",
            field=models.TextField(max_length=2000, unique=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="articlecategory",
            name="description",
            field=models.TextField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name="articlecategory",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="articlecategory",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="articlecomment",
            name="content",
            field=models.TextField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name="articlecomment",
            name="email",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="articlecomment",
            name="fullname",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="articletag",
            name="description",
            field=models.TextField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name="articletag",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="articletag",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="articles.articleimage",
            ),
        ),
    ]
