# Generated by Django 5.1.4 on 2025-01-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_articleimage_alter_article_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlecategory",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
