# Generated by Django 5.1.4 on 2025-01-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="email",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
