# Generated by Django 5.1.4 on 2025-01-09 18:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_newsletter_created_at_alter_newsletter_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="activated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="newsletter",
            name="activation_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="newsletter",
            name="data_processing",
            field=models.BooleanField(default=False),
        ),
    ]
