# Generated by Django 5.1.4 on 2025-01-09 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_newsletter_activated_newsletter_activation_token_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="newsletter", old_name="activated", new_name="is_active",
        ),
        migrations.RenameField(
            model_name="newsletter", old_name="created_at", new_name="subscribed_at",
        ),
    ]
