# Generated by Django 5.1.4 on 2025-01-09 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_rename_dataprocessing_newsletter_data_processing"),
    ]

    operations = [
        migrations.RenameField(
            model_name="newsletter", old_name="is_active", new_name="active",
        ),
    ]
