# Generated by Django 5.1.4 on 2025-01-16 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_rename_activation_token_newsletter_token"),
    ]

    operations = [
        migrations.RemoveField(model_name="newsletter", name="data_processing",),
    ]
