# Generated by Django 5.1.4 on 2025-02-24 12:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tours", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={"verbose_name": "Currency", "verbose_name_plural": "Currencies",},
        ),
        migrations.CreateModel(
            name="DestinationImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="destinations/images")),
                ("alt", models.CharField(max_length=255)),
                ("format", models.CharField(max_length=255, null=True)),
                ("mode", models.CharField(max_length=255, null=True)),
                ("size", models.FloatField(null=True)),
                ("width", models.IntegerField(null=True)),
                ("height", models.IntegerField(null=True)),
            ],
            options={
                "verbose_name": "Destination Image",
                "verbose_name_plural": "Destination Images",
            },
        ),
        migrations.CreateModel(
            name="DestinationThumbnail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="destinations/thumbnails")),
                ("alt", models.CharField(max_length=255)),
                ("format", models.CharField(max_length=255, null=True)),
                ("mode", models.CharField(max_length=255, null=True)),
                ("size", models.FloatField(null=True)),
                ("width", models.IntegerField(null=True)),
                ("height", models.IntegerField(null=True)),
            ],
            options={
                "verbose_name": "Destination Thumbnail",
                "verbose_name_plural": "Destination Thumbnails",
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={"verbose_name": "Language", "verbose_name_plural": "Languages",},
        ),
        migrations.CreateModel(
            name="Month",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={"verbose_name": "Month", "verbose_name_plural": "Months",},
        ),
        migrations.CreateModel(
            name="TimeZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={"verbose_name": "Timezone", "verbose_name_plural": "Timezones",},
        ),
        migrations.CreateModel(
            name="Destination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("country", models.CharField(max_length=255, unique=True)),
                ("area", models.FloatField(max_length=10)),
                ("population", models.SmallIntegerField()),
                ("total_travelers", models.IntegerField()),
                ("currencies", models.ManyToManyField(to="destinations.currency")),
                ("popular_tours", models.ManyToManyField(to="tours.tour")),
                ("images", models.ManyToManyField(to="destinations.destinationimage")),
                (
                    "thumbnail",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="destinations.destinationthumbnail",
                    ),
                ),
                ("languages", models.ManyToManyField(to="destinations.language")),
                ("time_to_travel", models.ManyToManyField(to="destinations.month")),
                (
                    "timezone",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="destinations.timezone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Destination",
                "verbose_name_plural": "Destinations",
            },
        ),
    ]
