# Generated by Django 5.1.4 on 2025-02-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destinations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="currency",
            name="ticker",
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
