# Generated by Django 5.1.4 on 2025-02-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destinations", "0003_rename_ticker_currency_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="language",
            name="code",
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
