# Generated by Django 5.1.4 on 2025-02-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destinations", "0004_language_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="language", name="name", field=models.CharField(max_length=255),
        ),
    ]
