# Generated by Django 5.1.4 on 2025-02-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destinations", "0006_destination_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="destination", name="population", field=models.IntegerField(),
        ),
    ]
