# Generated by Django 5.1.4 on 2025-02-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destinations", "0007_alter_destination_population"),
    ]

    operations = [
        migrations.RemoveField(model_name="destination", name="total_travelers",),
        migrations.AlterField(
            model_name="destination",
            name="area",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="destination",
            name="population",
            field=models.CharField(max_length=20),
        ),
    ]
