# Generated by Django 5.1.4 on 2025-02-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destinations", "0008_remove_destination_total_travelers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="destination",
            name="total_travelers",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
