# Generated by Django 5.1.4 on 2025-02-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destinations", "0009_destination_total_travelers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="language",
            name="code",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
