# Generated by Django 5.1.4 on 2025-02-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destinations", "0010_alter_language_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="destination",
            name="slug",
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
