# Generated by Django 5.1.6 on 2025-05-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="email",
            field=models.CharField(max_length=255),
        ),
    ]
