# Generated by Django 5.1.4 on 2025-05-28 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-creation_timestamp"],
                "verbose_name": "Account",
                "verbose_name_plural": "Accounts",
            },
        ),
        migrations.RenameField(
            model_name="user", old_name="created_at", new_name="creation_timestamp",
        ),
        migrations.RenameField(
            model_name="user", old_name="updated_at", new_name="modification_timestamp",
        ),
    ]
